name: Daily Gold Price Scraper

on:
  #8am/pm
  schedule:
    - cron: '0 0 * * *' 
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev chromium-browser

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-packages-${{ hashFiles('pkg_lockfile.lock') }}
          restore-keys: r-packages-

      - name: Install R packages
        run: |
          Rscript -e "install.packages('pak', repos='https://cloud.r-project.org')"
          Rscript -e "pak::pkg_install(c('netstat', 'tidyverse', 'dplyr', 'rvest', 'chromote'))"
        
      - name: Run scraper
        env:
          CHROMOTE_CHROME_PATH: /usr/bin/chromium-browser
        run: Rscript goldprices.R

      - name: Commit and push updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add prices.csv
          git commit -m "Update gold prices $(date +'%Y-%m-%d')" || echo "No changes"
          git push
